# Generated by Django 3.0.2 on 2020-02-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=16, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='HandbookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=255)),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task.Handbook')),
            ],
        ),
    ]
