# Generated by Django 3.0.2 on 2020-02-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0002_auto_20200202_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='version',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='handbook',
            unique_together={('name', 'version')},
        ),
    ]
