openapi: 3.0.2
info:
  title: 'Handbook API'
  version: '0.1'
  description: 'API для сервиса справочников'
paths:
  /terminology/handbooks/:
    get:
      operationId: listHandbooks
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0441\u043F\
        \u0438\u0441\u043A\u0430 \u0432\u0441\u0435\u0445 \u0441\u043F\u0440\u0430\
        \u0432\u043E\u0447\u043D\u0438\u043A\u043E\u0432"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                  - name: terms
                    short_name: t
                    description: ''
                    version: '0.2'
                    create_date: '2020-03-08 12:45:48'
                  - name: terms
                    short_name: t
                    description: ''
                    version: '0.1'
                    create_date: '2020-02-08 12:43:43'
                  - name: diseases
                    short_name: d
                    description: ''
                    version: '0.02'
                    create_date: '2020-02-08 12:45:48'
          description: ''
  /terminology/handbooks/{year}/{month}/{day}/:
    get:
      operationId: RetrieveActualHandbookList
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0441\u043F\
        \u0438\u0441\u043A\u0430 \u0441\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\
        \u043A\u043E\u0432, \u0430\u043A\u0442\u0443\u0430\u043B\u044C\u043D\u044B\
        \u0445 \u043D\u0430 \u0443\u043A\u0430\u0437\u0430\u043D\u043D\u0443\u044E\
        \ \u0434\u0430\u0442\u0443."
      parameters:
      - name: year
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: month
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: day
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                example:
                  - name: terms
                    short_name: t
                    description: ''
                    version: '0.1'
                    create_date: '2020-02-08 12:42:42'
                  - name: diseases
                    short_name: d
                    description: ''
                    version: '0.02'
                    create_date: '2020-02-08 12:45:48'
          description: ''
  /terminology/{handbook_name}/items/:
    get:
      operationId: listHandbookItems
      description: "\u041F\u043E\u043B\u0443\u0447\u0435\u043D\u0438\u0435 \u0441\u043F\
        \u0438\u0441\u043A\u0430 \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u043E\u0432\
        \ \u0441\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A\u0430 \u0443\
        \u043A\u0430\u0437\u0430\u043D\u043D\u043E\u0439 \u0432\u0435\u0440\u0441\u0438\
        \u0438 \u0438\u043B\u0438 \u0442\u0435\u043A\u0443\u0449\u0435\u0439 \u0432\
        \u0435\u0440\u0441\u0438\u0438, \u0435\u0441\u043B\u0438 \u043D\u0435 \u0443\
        \u043A\u0430\u0437\u0430\u043D\u043E \u044F\u0432\u043D\u043E."
      parameters:
      - name: handbook_name
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: version
        in: query
        required: false
        description: 'Версия справочника'
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
                example:
                  - handbook_name: 'terms'
                    code: '100'
                    content: 'some content'
          description: ''
    post:
      operationId: CreateHandbookItemList
      description: "\u0412\u0430\u043B\u0438\u0434\u0430\u0446\u0438\u044F \u044D\u043B\
        \u0435\u043C\u0435\u043D\u0442\u0430 \u0441\u043F\u0440\u0430\u0432\u043E\u0447\
        \u043D\u0438\u043A\u0430 \u0443\u043A\u0430\u0437\u0430\u043D\u043D\u043E\u0439\
        \ \u0432\u0435\u0440\u0441\u0438\u0438 \u0438\u043B\u0438 \u0442\u0435\u043A\
        \u0443\u0449\u0435\u0439 \u0432\u0435\u0440\u0441\u0438\u0438, \u0435\u0441\
        \u043B\u0438 \u043D\u0435 \u0443\u043A\u0430\u0437\u0430\u043D\u043E \u044F\
        \u0432\u043D\u043E."
      parameters:
      - name: handbook_name
        in: path
        required: true
        description: ''
        schema:
          type: string

      - name: version
        in: query
        required: false
        description: 'Версия справочника'
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                example:
                  - handbook_name: 'terms'
                    code: '100'
                    content: 'some content'
          description: ''
